name: Metaversal Comics
favicon: null
layout_spectrum: 0.5825619334354997
typography_spectrum: 0.567813906352967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7756315898150206
  lightness: 0.5759245087392628
  saturation: 0.9153194455429912
  rhythmicContrast: 0.2648252728395164
purpose: []
